name: Bug Report
labels: ["bug"]
description: 'File bugs that impact the flatpak version of Obsidian'
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        Please confirm that the conditions listed below have been met.
      options:
        - label: I have tested other [Obsidian builds (i.e., .tar.gz, .AppImage, .deb, etc)](https://github.com/obsidianmd/obsidian-releases/releases/latest) to confirm that this issue is flatpak-specific ([general Obsidian issues should be reported to the upstream issue tracker](https://forum.obsidian.md/c/bug-reports/7))
          required: true
        - label: [I have checked other filed issues](https://github.com/flathub/md.obsidian.Obsidian/issues?q=is%3Aissue) to confirm that this is a new flatpak-specific issue
          required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Please describe what happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Obsidian Version
      description: |
        Please list Obsidian version information from `flatpak info md.obsidian.Obsidian`
      render: 'bash session'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Sandbox Permissions
      description: |
        Please list sandbox permissions from `flatpak info md.obsidian.Obsidian --show-permissions`
      render: 'bash session'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Hardware Information
      description: |
        Please list hardware information from `lspci -nn | grep -E 'VGA|Display'` and `glxinfo -B`
      render: 'bash session'
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Information
      description: |
        Please list any additional system information such as the Linux distribution, desktop environment / window manager, and flatpak version
      render: 'bash session'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Logs
      description: |
        Please attach logs from `flatpak run --env=DEBUG_LOG=1 md.obsidian.Obsidian`
      render: 'bash session'
    validations:
      required: false
